describe('Spaceship coast to coast', function () {
    before(browser => browser.navigateTo('http://127.0.0.1:5500/KeepWhiteSpace/'));
    it('should work pls', function (grandParametreGenealogiquePourResterPoliEtJeLeLaisseEnCamelCasePourFairePropre) {
        grandParametreGenealogiquePourResterPoliEtJeLeLaisseEnCamelCasePourFairePropre.waitForElementVisible('body')
            // .pause("500")
            .sendKeys("body", browser.Keys.SPACE + browser.Keys.SPACE+ browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT )
            for(let izi = 0; izi < 500; izi++){
            grandParametreGenealogiquePourResterPoliEtJeLeLaisseEnCamelCasePourFairePropre.sendKeys("body", browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT+ browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT+ browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT+ browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT+ browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT+ browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT+ browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT+ browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT+ browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT + browser.Keys.LEFT)
            }
            // .assert.containsText('#result', 'You entered: BACK_SPACE')
      
    });
    after(browser => browser.end());
});