# Use root/example as user/password credentials
version: '3.1'

services:

  back:
    build: .
    restart: always
    ports:
      - "3012:3012"

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: john
      MYSQL_PASSWORD: doe
      MYSQL_DATABASE: spacegames
    ports:
      - "13306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql

  twoships:
    build: 
        dockerfile: Dockerfile
        context: ../../TwoShips
    ports:
        - "5000:80"

  behindasteroids:
    build: 
        dockerfile: Dockerfile
        context: ../../BehindAsteroids
    ports:
        - "7575:8080"
  keepwhitespace:
    build: 
        dockerfile: Dockerfile
        context: ../../KeepWhiteSpace
    ports:
        - "4243:80"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1


volumes:
  my-datavolume: