name: Nightwatch behind asteroid Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      working-directory: ./BehindAsteroid

    - name: Install xvfb
      run: sudo apt-get install xvfb 
      working-directory: ./BehindAsteroid

    # - name: Start the game
    #   run: npm run start
    #        sleep 180
           
    # - name: Start Local Server
    #   run: |
    #     npm install -g live-server
    #     live-server --port=8080 --watch="./target/index.html" &
    #     sleep 5
    # - name: Wait for Local Server
    #   run: wait-on http://127.0.0.1:5500/TwoShips/index.html
    # - name: Debug 
    #   run: ls ./

    - name: Run Nightwatch test
      run: xvfb-run --auto-servernum npm run nightwatchba -- --env chrome
      working-directory: ./BehindAsteroid

    # - name: Stop Local Server
    #   run: pkill -f "live-server"
