name: tests fonctionnels twoships

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      working-directory: ./TwoShips

    - name: Install xvfb
      run: sudo apt-get install xvfb 
      working-directory: ./TwoShips

    - name: Start Local Server
      run: |
        npm install -g live-server
        live-server --port=5500 --watch="./index.html" &
        sleep 5
      working-directory: ./TwoShips

    - name: Run Nightwatch tests 
      run: xvfb-run --auto-servernum npm run nightwatchts -- --env chrome
      working-directory: ./TwoShips
      
    - name: Stop Local Server
      run: pkill -f "live-server"
      working-directory: ./TwoShips
