name : test unitaire whitespace

on: 
  push:
  pull_request: 
    branches: [main]

jobs:
      tests:
        runs-on: ubuntu-latest
    
        strategy:
          matrix:
            node-version: [16.x,18.x,20.x]

        steps:
        - uses: actions/checkout@v2
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 16.13.x
            cache: npm
        - name: npm install
          run: npm ci
          working-directory: ./KeepWhiteSpace

        - name: tests
          run: npm test
          working-directory: ./KeepWhiteSpace

